# Generated by Django 4.2.4 on 2023-09-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_description_alter_listing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='currentBid',
        ),
    ]
